version: '3.8'

services:
  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: ${DEFAULT_DBSERVER} #Use an environmental variable to set the default server
    ports:
      - "8080:8080"  # <Host Port>:<Container Port>