version: '3.8'

services:
  authelia:
    container_name: authelia
    image: docker.io/authelia/authelia:latest
    restart: unless-stopped
    volumes:
      - nfs-authelia-config:/config
      - nfs-authelia-secrets:/secrets
    networks:
      net: 
        aliases: []
    expose: 
      - 9091
    environment:
      TZ: America/Los_Angeles
      AUTHELIA_JWT_SECRET_FILE: /secrets/JWT_SECRET
      AUTHELIA_SESSION_SECRET_FILE: /secrets/SESSION_SECRET
      AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE: /secrets/STORAGE_PASSWORD
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: /secrets/STORAGE_ENCRYPTION_KEY
  lldap:
    container_name: lldap
    hostname: lldap
    image: lldap/lldap:stable
    restart: unless-stopped
    networks:
      - net
    expose:
      - 3890   # LDAP
      - 17170  # Web UI
    env_file:
      - container-vars.env
    volumes:
      - nfs-lldap-data:/data
      - nfs-lldap-secrets:/secrets

volumes: 
  nfs-authelia-config: 
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_SERVER},rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4
      device: :${NFS_PATH}/authelia-config
  nfs-authelia-secrets: 
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_SERVER},rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4
      device: :${NFS_PATH}/authelia-secrets

  nfs-lldap-data: 
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_SERVER},rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4
      device: :${NFS_PATH}/lldap-config
  nfs-lldap-secrets: 
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_SERVER},rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4
      device: :${NFS_PATH}/lldap-secrets
  
networks:
  net:
    external: true
    name: net