version: "3.9"
services:
  codeserver:
    container_name: Code-Server
    image: ghcr.io/linuxserver/code-server
    security_opt:
      - no-new-privileges:false
    restart: on-failure:5
    ports:
      - 8377:8443
    volumes:
      - nfs-codeserver:/config
    environment:
      TZ: America/Los_Angeles
      #PROXY_DOMAIN: codeserver.yourname.synology.me
      PASSWORD: ${PASS}
      SUDO_PASSWORD: ${SUDO_PASS}

volumes: 
  nfs-codeserver: 
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_SERVER},rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4
      device: :${NFS_PATH} # Path for the config data folder (e.g. /volume1/docker/corosync)