version: "3.6"
services:
  flame:
    container_name: flame
    image: pawelmalak/flame
    restart: unless-stopped
    ports:
      - 5005:5005
    volumes:
      - nfs-flame:/app/data
    environment:
      TZ: America/Los_Angeles
      #PROXY_DOMAIN: codeserver.yourname.synology.me
      PASSWORD: ${PASS}

volumes: 
  nfs-flame: 
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_SERVER},rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4
      device: :${NFS_PATH} # Path for the config data folder (e.g. /volume1/docker/corosync)