version: '3'

services:
  homarr:
    image: ghcr.io/ajnart/homarr:latest
    container_name: homearr
    volumes:
      # - /var/run/docker.sock:/var/run/docker.sock #optional for docker integration
      - nfs-homarr-configs:/app/data/configs
      - nfs-homarr-icons:/app/public/icons
      - nfs-homarr-data:/data
    ports:
      - "47575:7575"  # <Host Port>:<Container Port>
    restart: unless-stopped

volumes: 
  nfs-homarr-configs: 
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_SERVER},rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4
      device: :${NFS_PATH}/configs
  nfs-homarr-icons: 
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_SERVER},rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4
      device: :${NFS_PATH}/icons
  nfs-homarr-data: 
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_SERVER},rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4
      device: :${NFS_PATH}/data