version: "3"
services:
  readarr:
    container_name: readarr
    image: lscr.io/linuxserver/readarr:develop
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports: 
      - 8787:8787
    volumes: 
      - local-readarr:/config
      - local-root:/media
    environment:
      TZ: America/Los_Angeles
      PUID: ${PUID} # Ex for Synology: 1026
      PGID: ${PGID} # Ex for Synology: 100

  readarr-audio:
    container_name: readarr-audio
    image: lscr.io/linuxserver/readarr:develop
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports: 
      - 8788:8787
    volumes: 
      - local-readarr-audio:/config
      - local-root:/media
    environment:
      TZ: America/Los_Angeles
      PUID: ${PUID} # Ex for Synology: 1026
      PGID: ${PGID} # Ex for Synology: 100

#Local volumes for fastest downloads (1Gbps = ~110MB/s)
volumes:

#MEDIA_ROOT is the root folder of the structure (e.g. /media), this should contain your plex/jellyfin library and the download folders
  local-root:
    driver: local 
    driver_opts:
      type: none
      o: bind
      device: ${MEDIA_ROOT}

#CONFIG_PATH is for application configuration directories, this can be anywhere you want to store the configs for each application
  local-readarr:
    driver: local 
    driver_opts:
      type: none
      o: bind
      device: ${CONFIG_PATH}/readarr
  local-readarr-audio:
    driver: local 
    driver_opts:
      type: none
      o: bind
      device: ${CONFIG_PATH}/readarr-audio
