version: '3.8'

services:
  nginx-proxy-manager:
    image: lepresidente/nginxproxymanager:latest #Crowdsec community supported image with NPM remediation component baked in
    container_name: nginx-proxy-manager
    restart: always
    volumes:
      - nfs-data:/data
      - nfs-letsencrypt:/etc/letsencrypt
    ports: # <Host Port>:<Container Port>
      - "80:80" # For proxying on HTTP
      - "443:443" # For proxying on HTTPS
      - "81:81" # For the admin portal

volumes: 
  nfs-data: 
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_SERVER},rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4
      device: :${NFS_PATH}/data # Path for the NPM data folder
  nfs-letsencrypt: 
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_SERVER},rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4
      device: :${NFS_PATH}/letsencrypt # Path for the NPM LetsEncrypt folder