version: '3.8'

services:
  vuegraf:
    image: jertel/vuegraf:latest
    container_name: vuegraf
    restart: always
    volumes:
      - nfs:/opt/vuegraf/conf
    

# Option 1: Use an existing volume
#volumes:
#  MYVOLUMENAME: # Replace this with your existing volume name
#    external: true

# Options 2: Create your own local volume
#volumes:
#  nginx-proxy-manager: 

# Option 3: Create a volume that maps to a NFS volume (set NFS_SERVER and NFS_PATH to the necessary NFS connection information)
volumes: 
  nfs: 
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_SERVER},rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4
      device: :${NFS_PATH} # Path for the NPM data folder