# WARNING: Won't work until dashy is updated to support directories for the conf.yml file
version: '3.8'

services:
  dashy:
    image: lissy93/dashy:latest
    container_name: dashy
    volumes:
      - nfs:/app/public/conf.yml # match the first part to the volume section that is uncommented below
    ports:
      - "4000:80"  # <Host Port>:<Container Port>
    restart: always

# Option 1: Use an existing volume
#volumes:
#  MYEXISTINGVOLUMENAME: # Replace this with your existing volume name
#    external: true

# Options 2: Create your own local volume
#volumes:
#  dashy: 

# Option 3: Create a volume that maps to a NFS volume (set NFS_SERVER and NFS_PATH to the necessary NFS connection information)
volumes: 
  nfs: 
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_SERVER},rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4
      device: :${NFS_PATH} # Env variable should be the full path to the config file (e.g. /volume1/docker/dashy/my-local-conf.yml on a synology NAS)