---
- name: SSHD - Copy Key for user and disable password login
  hosts: all
  become: yes  # To elevate privileges to perform administrative tasks

  tasks:
    - name: Copy SSH Key to user's authorized_keys file
      authorized_key:
        # Make sure to have your variable set at runtime using something like: --extra-vars "username=foo"
        user: "{{ username }}"
        key: "{{ lookup('file', '/home/{{ username }}/.ssh/id_rsa.pub') }}" 
        state: present
        exclusive: true

    - name: Configure SSHD to deny password logins and enable public key logins
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: '^(PasswordAuthentication\s+)yes$', line: 'PasswordAuthentication no' }
        - { regexp: '^(PubkeyAuthentication\s+)no$', line: 'PubkeyAuthentication yes' }
        - { regexp: '^(#PubkeyAuthentication\s+)yes$', line: 'PubkeyAuthentication yes' }
      notify: Restart SSHD

  handlers:
    - name: Restart SSHD
      service:
        name: sshd
        state: restarted
