---
- name: SSHD - Copy Key for user and disable password login
  hosts: all
  become: yes  # To elevate privileges to perform administrative tasks

  tasks:
    - name: Copy SSH Key to user's authorized_keys file
      authorized_key:
        # Make sure to have your variable set at runtime using something like: --extra-vars "username=foo"
        user: "{{ username }}"
        # Make sure the public key you want is in the user's home directory on the ansible server
        key: "{{ lookup('file', '/home/{{ username }}/.ssh/id_rsa.pub') }}" 
        state: present
        # Set the below to true if you want this to be the only key for that user
        exclusive: true

    - name: Configure SSHD to deny password logins and enable public key logins
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: '^(PasswordAuthentication\s+)yes$', line: 'PasswordAuthentication no' } # Disable Password Auth
        - { regexp: '^(PubkeyAuthentication\s+)no$', line: 'PubkeyAuthentication yes' } # Change PubkeyAuthentication no to yes
        - { regexp: '^(#PubkeyAuthentication\s+)yes$', line: 'PubkeyAuthentication yes' } # Uncomment Pubkey Authentication yes
      notify: Restart SSHD # trigger a sshd restart to activate the new configuration

  handlers:
    - name: Restart SSHD
      service:
        name: sshd
        state: restarted
