# Variables to make sure you configure:
# - vmName: the name to assign to the created VM
# - templateName: the name of the template you want to clone the VM from
# - proxmox_host: the proxmox host you will be logging into and where the VM will be deployed (if it's in a cluster, you can migrate it later)
# - storage_name: the name of the storage volume you want to use to store the VM files on the proxmox host
- name: Proxmox - Deploy VM from template
  hosts: pm1
  vars:
    name: debian
  tasks:
    - set_fact:
        vmName: "Debian12" # VM Name
        templateName: "Devian12-Template" #Template to use
        proxmox_host: "pm1.carouselsystems.net"
        storage_name: "NAS-VMs"
    - proxmox_kvm:
        api_user: root@pam
        api_password: 
        api_host: "{{ proxmox_host }}"
        clone: "{{ templateName }}"
        full: yes
        name: "{{ vmName }}"
        node: pm1
        format: qcow2
        timeout: 500 # Note: This can take a while, adjust as necessary

    - name: start vm
      proxmox_kvm: 
        api_user: root@pam
        api_password: 
        api_host: pm1.carouselsystems.net 
        name: "{{ vmName }}"
        node: pm1
        state: started